# Generated by Django 5.2.7 on 2026-04-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название акции')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Скидка (%)')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(verbose_name='Действует до')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Дисконтная программа',
                'verbose_name_plural': 'Дисконтные программы',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['time_create'], name='DiscPro_dis_time_cr_beab38_idx'), models.Index(fields=['slug'], name='DiscPro_dis_slug_c2bfbc_idx')],
            },
        ),
    ]
