# Generated by Django 5.2.7 on 2026-05-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscPro', '0002_category_tagpost_discount_cat_discount_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model', verbose_name='Файл')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
