# Generated by Django 5.2.7 on 2026-05-04 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscPro', '0003_uploadfiles_discount_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название поставщика')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма покупок')),
                ('discount_card_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Номер дисконтной карты')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-total_purchases'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_level', models.CharField(default='Обычный', max_length=50, verbose_name='Уровень лояльности')),
                ('bonus_points', models.IntegerField(default=0, verbose_name='Бонусные баллы')),
                ('personal_discount', models.IntegerField(default=0, verbose_name='Персональная скидка (%)')),
                ('preferences', models.TextField(blank=True, verbose_name='Предпочтения')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='DiscPro.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиентов',
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата использования')),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма покупки')),
                ('saved_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сэкономлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='DiscPro.client', verbose_name='Клиент')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='DiscPro.discount', verbose_name='Дисконт')),
            ],
            options={
                'verbose_name': 'Использование дисконта',
                'verbose_name_plural': 'Использования дисконтов',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='DiscPro.supplier', verbose_name='Поставщик'),
        ),
    ]
